fullnameOverride: capsule
manager:
    # Manager RBAC
  rbac:
    create: true
    existingClusterRoles:
    - "view"
    existingRoles:
    - "some-role"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 128Mi
