- op: add
  path: /webhooks/0/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/1/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/2/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/4/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/5/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/6/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/7/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/8/namespaceSelector
  value:
    matchExpressions:
      - key: capsule.clastix.io/tenant
        operator: Exists
- op: add
  path: /webhooks/8/rules/0/scope
  value: Namespaced
