# Default values for capsule.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

manager:
  image:
    repository: quay.io/clastix/capsule
    pullPolicy: IfNotPresent
    tag: ''
  # Additional manager options
  options:
    logLevel: '4'
    forceTenantPrefix: true
    capsuleUserGroup:
    protectedNamespaceRegex:
    allowIngressHostnameCollision: false
    allowTenantIngressHostnamesCollision: true
  livenessProbe:
    httpGet:
      path: /healthz
      port: 10080
  readinessProbe:
    httpGet:
      path: /readyz
      port: 10080
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi

sidecar:
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    pullPolicy: IfNotPresent
    tag: "v0.5.0"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

jobs:
  image:
    repository: bitnami/kubectl
    pullPolicy: IfNotPresent
    tag: "1.18"

capsule-proxy:
  enabled: false
  replicaCount: 1
  hostNetwork: false
  hostPort: false
  imagePullSecrets: []
  image:
    repository: quay.io/clastix/capsule-proxy
    pullPolicy: IfNotPresent
    tag: ""
  options:
    listeningPort: 9001
    logLevel: '5'
    k8sControlPlaneUrl: https://kubernetes.default.svc
    capsuleUserGroup: capsule.clastix.io
    oidcUsernameClaim: preferred_username
    enableSSL: false
    SSLDirectory: /opt/capsule-proxy
    SSLCertFileName: tls.crt
    SSLKeyFileName: tls.key
    generateCertificates: false
  serviceAccount:
    create: true
    annotations: {}
    name: "capsule-proxy"
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP # ClusterIP | NodePort | LoadBalancer
    port: 9001
    portName: proxy
    nodePort:
    annotations: {}
    labels: {}
  ingress:
    enabled: false
    annotations: {}
    hosts:
    - host: kube.clastix.io
      paths: [ "/" ]
    tls: []
  resources: 
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}

mutatingWebhooksTimeoutSeconds: 30
validatingWebhooksTimeoutSeconds: 30
imagePullSecrets: []
serviceAccount:
  create: true
  annotations: {}
  name: "capsule"
podAnnotations: {}
priorityClassName: '' #system-cluster-critical
nodeSelector: {}
tolerations: []
replicaCount: 1
affinity: {}
podSecurityPolicy:
  enabled: false
