# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tenants.capsule.clastix.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          namespace: capsule-system
          name: capsule-webhook-service
          path: /convert
          port: 443
      conversionReviewVersions:
        - v1alpha1
        - v1beta1
