apiVersion: v1
kind: Service
metadata:
  name: {{ include "capsule.fullname" . }}-controller-manager-metrics-service
  labels:
    {{- include "capsule.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8080
    name: metrics
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "capsule.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
