name: Autogen API Docs

on:
  push:
    branches: [ "*" ]
    paths:
      - 'charts/capsule/crds/**'
  pull_request:
    branches: [ "*" ]
    paths:
      - 'charts/capsule/crds/**'

  workflow_dispatch:

jobs:
  autogen:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: "Install code generator (fybrik.io/crdoc@latest)"
        run: go install fybrik.io/crdoc@latest
      - name: Autogen APIs
        run: crdoc --resources config/crd/bases --output docs/content/general/references.md
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.2
        env:
          key: main        
          files: docs/content/general/references.md
