name: docs-lint
permissions: {}

on:
  push:
    branches: [ "*" ]
    paths:
      - '.github/workflows/docs-lint.yml'
      - 'docs/content/**'
  pull_request:
    branches: [ "*" ]
    paths:
      - '.github/workflows/docs-lint.yml'
      - 'docs/content/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spelling:
    name: Spell Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18
      - run: make docs-lint