name: docs-lint
permissions: {}

on:
  push:
    branches: [ "*" ]
    paths:
      - '.github/workflows/docs-lint.yml'
      - 'docs/content/**'
  pull_request:
    branches: [ "*" ]
    paths:
      - '.github/workflows/docs-lint.yml'
      - 'docs/content/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spelling:
    name: Spell Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 18
      - run: make docs-lint