name: docs-lint
permissions: {}

on:
  push:
    branches: [ "*" ]
    paths:
      - '.github/workflows/docs-lint.yml'
      - 'docs/content/**'
  pull_request:
    branches: [ "*" ]
    paths:
      - '.github/workflows/docs-lint.yml'
      - 'docs/content/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spelling:
    name: Spell Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 18
      - run: make docs-lint