name: e2e

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  kind:
    name: Kubernetes
    strategy:
      matrix:
        k8s-version: ['v1.16.15', 'v1.17.11', 'v1.18.8', 'v1.19.4', 'v1.20.7', 'v1.21.2', 'v1.22.0']
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache Go modules and Docker images
        uses: actions/cache@v1
        env:
          cache-name: gomod-docker
        with:
          path: |
            ~/go/pkg/mod
            /var/lib/docker
            /home/runner/work/capsule/capsule
          key: ${{ matrix.k8s-version }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ matrix.k8s-version }}-build-
            ${{ matrix.k8s-version }}-
      - run: make manifests
      - name: Checking if manifests are disaligned
        run: test -z "$(git diff 2> /dev/null)"
      - name: Checking if manifests generated untracked files
        run: test -z "$(git ls-files --others --exclude-standard 2> /dev/null)"
      - name: Installing Ginkgo
        run: go get github.com/onsi/ginkgo/ginkgo
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.6'
      - uses: engineerd/setup-kind@v0.5.0
        with:
          skipClusterCreation: true
          version: v0.11.1
      - uses: azure/setup-helm@v1
        with:
          version: 3.3.4
      - name: e2e testing
        run: make e2e/${{ matrix.k8s-version }}
