name: Test charts
permissions: {}

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3
      - name: Linting Chart
        run: helm lint ./charts/capsule
      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@e8788873172cb653a90ca2e819d79d65a66d4e76 # v2.4.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ./.github/configs/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint --debug --config ./.github/configs/ct.yaml --lint-conf ./.github/configs/lintconf.yaml
      - name: Run docs-testing (helm-docs)
        id: helm-docs
        run: |
          make helm-docs
          if [[ $(git diff --stat) != '' ]]; then
            echo -e '\033[0;31mDocumentation outdated! (Run make helm-docs locally and commit)\033[0m ❌'
            git diff --color
            exit 1
          else
            echo -e '\033[0;32mDocumentation up to date\033[0m ✔'
          fi

      # ATTENTION: This is a workaround for the upcoming ApiVersion Conversions for the capsule CRDs
      # With this workflow the current docker image is build and loaded into kind, otherwise the install fails
      # In the future this must be removed and the chart-testing-action must be used
      - name: Run chart-testing (install)
        run: make helm-test
        if: steps.list-changed.outputs.changed == 'true'

      ## Create KIND Cluster
      - name: Create kind cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        if: steps.list-changed.outputs.changed == 'true'
      # Install Required Operators/CRDs
      - name: Prepare Cluster Operators/CRDs
        run: |
          # Cert-Manager CRDs
          kubectl create -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.crds.yaml
          
          # Prometheus CRDs
          kubectl create -f https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.58.0/bundle.yaml
        if: steps.list-changed.outputs.changed == 'true'
      # Install Charts
      - name: Run chart-testing (install)
        run: ct install --debug --config ./.github/configs/ct.yaml
        if: steps.list-changed.outputs.changed == 'true'
